name: Rebuild Website

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
    contents: write
    deployments: write
    id-token: write
    pages: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update:
    name: "Rebuild website"
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: thetanerd-com
          directory: public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
